name: Deploy React Web App to Azure Static Web Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy jobs
    steps:
      - uses: actions/checkout@v2
      - name: Build React App
        run: |
          npm install
          npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "/"
        output_location: "build"
